# Changes here will be overwritten by Copier
_commit: a08e36f
_src_path: C:\Users\m\MyMain\dev\pypackage-template-fork
add_me_as_contributor: true
copyright_year: '2023'
documentation: true
email: 34j.95a2p@simplelogin.com
full_name: 34j
github_username: 34j
initial_commit: true
open_source_license: CC0 1.0 Universal
package_name: jinja2_shell
project_name: jinja2-shell
project_short_description: Jinja2 Extension for running shell commands
project_slug: jinja2-shell
run_poetry_install: false
setup_github: true
setup_pre_commit: false

